import fs from "fs";
import path from "path";
import { parseFile } from "music-metadata";
import {
  createElevenLabsClient,
  DEFAULT_MODEL_ID,
  DEFAULT_VOICE_ID,
  ensureDir,
  fileExists,
  parseArgs,
  PATHS,
  ROOT,
  streamToBuffer,
  VOICE_SETTINGS,
  VOICEOVER_SEGMENTS,
} from "../src/lib/elevenlabs";

const concatMp3Buffers = (buffers: Buffer[]): Buffer => {
  return Buffer.concat(buffers);
};

const main = async () => {
  const { force, voiceId, modelId } = parseArgs();
  const voice = voiceId ?? process.env.ELEVENLABS_VOICE_ID ?? DEFAULT_VOICE_ID;
  const model = modelId ?? process.env.ELEVENLABS_MODEL_ID ?? DEFAULT_MODEL_ID;

  ensureDir(path.dirname(PATHS.voiceover));
  ensureDir(PATHS.voiceoverSegments);

  if (fileExists(PATHS.voiceover) && !force) {
    console.log(`✓ Voiceover exists: ${PATHS.voiceover} (use --force to regenerate)`);
    return;
  }

  console.log(`Generating Arabic voiceover… voice=${voice} model=${model}`);
  const client = createElevenLabsClient();
  const segmentBuffers: Buffer[] = [];
  const segmentMeta: { id: string; text: string; durationSeconds: number }[] = [];

  for (const segment of VOICEOVER_SEGMENTS) {
    const segPath = path.join(PATHS.voiceoverSegments, `${segment.id}.mp3`);
    console.log(`  → ${segment.id}`);

    const settings = VOICE_SETTINGS[segment.style];
    const stream = await client.textToSpeech.convert(voice, {
      text: segment.text,
      modelId: model,
      outputFormat: "mp3_44100_128",
      voiceSettings: {
        stability: settings.stability,
        similarityBoost: settings.similarityBoost,
        style: settings.style,
        useSpeakerBoost: true,
      },
    });

    const buffer = await streamToBuffer(stream);
    fs.writeFileSync(segPath, buffer);
    segmentBuffers.push(buffer);

    const meta = await parseFile(segPath);
    segmentMeta.push({
      id: segment.id,
      text: segment.text,
      durationSeconds: meta.format.duration ?? 0,
    });
    console.log(`    ✓ ${(meta.format.duration ?? 0).toFixed(1)}s`);
  }

  const combined = concatMp3Buffers(segmentBuffers);
  fs.writeFileSync(PATHS.voiceover, combined);

  const totalSpeechSeconds = segmentMeta.reduce((sum, s) => sum + s.durationSeconds, 0);
  const durationSeconds = totalSpeechSeconds;
  const durationFrames = Math.round(totalSpeechSeconds * 60);
  let cursorSec = 0;
  const scenes = segmentMeta.map((s) => {
    const start = cursorSec;
    cursorSec += s.durationSeconds + 0.35;
    return {
      id: s.id,
      text: s.text,
      startSeconds: start,
      durationSeconds: s.durationSeconds,
    };
  });

  fs.writeFileSync(
    PATHS.voiceoverManifest,
    JSON.stringify(
      {
        voiceId: voice,
        modelId: model,
        durationSeconds,
        durationFrames,
        scenes,
        generatedAt: new Date().toISOString(),
      },
      null,
      2,
    ),
  );

  fs.writeFileSync(
    path.join(ROOT, "src", "audio", "voiceover-meta.ts"),
    `/** Auto-generated by npm run voiceover — do not edit */\nexport const VOICEOVER_DURATION_FRAMES = ${durationFrames};\nexport const VOICEOVER_DURATION_SECONDS = ${durationSeconds};\n`,
  );

  console.log(`\n✓ Saved ${PATHS.voiceover}`);
  console.log(`✓ Manifest ${PATHS.voiceoverManifest}`);
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
